services:
  - type: web
    name: my-products-api
    env: node
    region: oregon
    buildCommand: npm ci
    startCommand: node src/index.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
